# Generated by Django 5.1.6 on 2025-03-06 12:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('kullanici_tipi', models.CharField(choices=[('ogrenci', 'Öğrenci'), ('yurt_yetkilisi', 'Yurt Yetkilisi'), ('sehir_yetkilisi', 'Şehir Yetkilisi'), ('turkiye_yetkilisi', 'Türkiye Yetkilisi')], max_length=20)),
                ('groups', models.ManyToManyField(blank=True, related_name='customuser_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='customuser_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Sehir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('yetkili', models.ForeignKey(blank=True, limit_choices_to={'kullanici_tipi': 'sehir_yetkilisi'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feedbackApp.customuser')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_city', to='feedbackApp.sehir'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ilgili_sehir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='feedbackApp.sehir'),
        ),
        migrations.CreateModel(
            name='Yemek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('ogun', models.CharField(choices=[('kahvaltı', 'Kahvaltı'), ('akşam', 'Akşam')], max_length=20)),
                ('tarih', models.DateField()),
                ('sehir', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedbackApp.sehir')),
            ],
        ),
        migrations.CreateModel(
            name='YemekListesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField()),
                ('ogun', models.CharField(choices=[('kahvaltı', 'Kahvaltı'), ('akşam', 'Akşam')], max_length=20)),
                ('yemek_1', models.CharField(blank=True, max_length=100, null=True)),
                ('yemek_2', models.CharField(blank=True, max_length=100, null=True)),
                ('yemek_3', models.CharField(blank=True, max_length=100, null=True)),
                ('yemek_4', models.CharField(blank=True, max_length=100, null=True)),
                ('yemek_5', models.CharField(blank=True, max_length=100, null=True)),
                ('yemek_6', models.CharField(blank=True, max_length=100, null=True)),
                ('yemek_7', models.CharField(blank=True, max_length=100, null=True)),
                ('yemek_8', models.CharField(blank=True, max_length=100, null=True)),
                ('yemek_9', models.CharField(blank=True, max_length=100, null=True)),
                ('yemek_10', models.CharField(blank=True, max_length=100, null=True)),
                ('il', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackApp.sehir')),
            ],
        ),
        migrations.CreateModel(
            name='YemekListesiGuncelleme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excel_dosyasi', models.FileField(upload_to='yemek_listeleri/')),
                ('yuklenme_tarihi', models.DateTimeField(auto_now_add=True)),
                ('sehir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackApp.sehir')),
            ],
        ),
        migrations.CreateModel(
            name='YemekYorumu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yorum', models.TextField()),
                ('duygu_durumu', models.CharField(choices=[('iyi', 'İyi'), ('notr', 'Nötr'), ('kotu', 'Kötü')], default='notr', max_length=10)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('yemek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackApp.yemek')),
            ],
        ),
        migrations.CreateModel(
            name='Yurt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('sehir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackApp.sehir')),
            ],
        ),
    ]
