# Generated by Django 5.1.7 on 2025-03-07 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='ilgili_sehir',
        ),
        migrations.RemoveField(
            model_name='sehir',
            name='yetkili',
        ),
        migrations.AddField(
            model_name='customuser',
            name='sehir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='feedbackApp.sehir'),
        ),
    ]
