# Generated by Django 5.1.6 on 2025-03-07 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackApp', '0002_remove_customuser_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yemekyorumu',
            name='duygu_durumu',
        ),
        migrations.AddField(
            model_name='yemekyorumu',
            name='sehir_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='feedbackApp.sehir'),
        ),
        migrations.AddField(
            model_name='yemekyorumu',
            name='yorum_puanı',
            field=models.CharField(choices=[(0, '0 - Anlamsız'), (1, '1 - Yenilmez'), (2, '2 - Kötü'), (3, '3 - Orta'), (4, '4 - İyi'), (5, '5 - Mükemmel')], default='-1', max_length=10),
        ),
        migrations.AddField(
            model_name='yemekyorumu',
            name='yurt',
            field=models.TextField(default='yurtsuz'),
        ),
    ]
