# Generated by Django 5.1.6 on 2025-03-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackApp', '0003_remove_yemekyorumu_duygu_durumu_yemekyorumu_sehir_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yemekyorumu',
            name='yemek',
            field=models.TextField(),
        ),
    ]
