# Generated by Django 5.1.6 on 2025-03-08 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackApp', '0005_customuser_yurt_yemekyorumu_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='yurt',
            field=models.CharField(max_length=100),
        ),
    ]
