# Generated by Django 5.1.6 on 2025-03-08 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackApp', '0008_alter_customuser_yurt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='yurt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yurt', to='feedbackApp.yurt'),
        ),
    ]
