# Generated by Django 5.1.6 on 2025-03-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackApp', '0009_alter_customuser_yurt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yemekyorumu',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='yemek_foto/'),
        ),
    ]
