# Generated by Django 5.1.6 on 2025-03-09 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackApp', '0010_alter_yemekyorumu_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ozet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olusturma_tarih', models.DateTimeField(auto_now_add=True)),
                ('ozet_tarih', models.DateField()),
                ('ozet_tur', models.CharField(choices=[('gunluk', 'gunluk'), ('haftalık', 'haftalık'), ('aylık', 'aylık')], max_length=100)),
                ('kapsam', models.CharField(choices=[('yurt', 'yurt'), ('sehir', 'şehir'), ('turkiye', 'türkiye')], max_length=100)),
                ('yurt', models.CharField(max_length=255)),
                ('ozet', models.TextField()),
                ('sehir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackApp.sehir')),
            ],
        ),
    ]
