# Generated by Django 5.1.6 on 2025-03-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackApp', '0011_ozet'),
    ]

    operations = [
        migrations.AddField(
            model_name='yemekyorumu',
            name='foto_betimleme',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yemekyorumu',
            name='yorum_onem',
            field=models.CharField(choices=[(1, '1 - Düşük'), (2, '2 - Önemsiz'), (3, '3 - Orta'), (4, '4 - Önemli'), (5, '5 - Kritik')], default='0', max_length=10),
        ),
    ]
