# Generated by Django 5.1.6 on 2025-03-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackApp', '0012_yemekyorumu_foto_betimleme_yemekyorumu_yorum_onem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yemekyorumu',
            name='yorum_onem',
            field=models.CharField(choices=[(0, '0 - Anlamsız'), (1, '1 - Düşük'), (2, '2 - Önemsiz'), (3, '3 - Orta'), (4, '4 - Önemli'), (5, '5 - Kritik')], default='0', max_length=10),
        ),
    ]
