# Generated by Django 5.1.6 on 2025-03-11 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackApp', '0013_alter_yemekyorumu_yorum_onem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ozet',
            name='yurt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
