# Generated by Django 5.1.6 on 2025-03-11 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackApp', '0014_alter_ozet_yurt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ozet',
            name='sehir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='feedbackApp.sehir'),
        ),
    ]
