# Generated by Django 5.1.6 on 2025-03-11 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackApp', '0015_alter_ozet_sehir'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yemekyorumu',
            old_name='sehir_id',
            new_name='sehir',
        ),
    ]
