# Generated by Django 5.1.6 on 2025-03-11 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackApp', '0016_rename_sehir_id_yemekyorumu_sehir'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yemekyorumu',
            old_name='sehir',
            new_name='sehir_id',
        ),
    ]
